include:
  - project: sre/gitlab-ci-templates
    ref: v1
    file:
      - /shared/build-and-push-image.yml
      - /shared/deploy-kubefiles.yml
      - /shared/upload-to-aliyun-oss.yml
stages:
  - build
  - upload
  - deploy
  - notification

.mix_install_deps:
  interruptible: true
  image: registry.tapsvc.com/public/node18-buster:pnpm7.27.0-1.0.0
  tags:
    - node
  before_script:
    - npm config set registry https://nexus.tapsvc.com/repository/npm-taptap
    - export NODE_OPTIONS=--max_old_space_size=4096
    - yarn install --cache-folder .yarn-cache
  cache:
    - key:
        files:
          - yarn.lock
          - .npmrc
      paths:
        - .yarn-cache

.mixin_build:
  stage: build
  interruptible: true
  environment:
    name: independent
  extends:
    - .mix_install_deps
  artifacts:
    expire_in: 1 week

.mixin_upload:
  stage: image-assets
  environment:
    name: independent
  variables:
    GIT_STRATEGY: none
  extends:
    - .upload-to-aliyun-oss

.mixin_slack:
  extends:
    - .mix_install_deps
  script:
    - git --version
    - npm i -g zx
    - source ./scripts/slack-definition.sh
    - chmod -R 777 ./scripts && ./scripts/slack-notification

.cn_master_rules:
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      changes:
        - cn/**/*
        - package.json
        - .gitlab-ci.yml
        - .ci/**/*
        - dockerfiles/**/*

.cn_mr_rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - cn/**/*
        - package.json
        - .gitlab-ci.yml
        - .ci/**/*
        - dockerfiles/**/*

.hk_master_rules:
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      changes:
        - hk/**/*
        - package.json
        - .gitlab-ci.yml
        - .ci/**/*
        - dockerfiles/**/*

.hk_mr_rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - hk/**/*
        - package.json
        - .gitlab-ci.yml
        - .ci/**/*
        - dockerfiles/**/*

# 国内 构建
build_cn:
  stage: build
  extends:
    - .mixin_build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - cn/**/*
        - package.json
        - .gitlab-ci.yml
        - .ci/**/*
        - dockerfiles/**/*
      variables:
        APP_PUBLIC_PATH: https://tds-preview.xdrnd.cn
        APP_ROUTER_BASE_URL: /tapsdk-doc-cn-$CI_MERGE_REQUEST_ID/
    - if: $CI_COMMIT_BRANCH == "master"
      changes:
        - cn/**/*
        - package.json
        - .gitlab-ci.yml
        - .ci/**/*
        - dockerfiles/**/*
      variables:
        APP_PUBLIC_PATH: https://developer.taptap.cn
        APP_ROUTER_BASE_URL: /docs/
  script:
    - yarn run build-cn:preview
  artifacts:
    paths:
      - cn/build
upload_mr_assets_cn:
  stage: upload
  extends:
    - .mixin_upload
    - .cn_mr_rules
  variables:
    ALIYUN_OSS_BUCKET: tds-abd-sh
    ALIYUN_OSS_ENDPOINT: oss-cn-shanghai-internal.aliyuncs.com
    SRC_PATH: cn/build
    DEST_PATH: preview/tapsdk-doc-cn-$CI_MERGE_REQUEST_ID
  needs:
    - build_cn
mr_slack_cn:
  stage: notification
  extends:
    - .mixin_slack
    - .cn_mr_rules
  variables:
    BUILD_LOCATION: cn
    APP_PUBLIC_PATH: https://tds-preview.xdrnd.cn
    APP_ROUTER_BASE_URL: /tapsdk-doc-cn-$CI_MERGE_REQUEST_ID/
  needs:
    - upload_mr_assets_cn
  allow_failure: true
# hk 构建
build_hk:
  stage: build
  extends:
    - .mixin_build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - hk/**/*
        - package.json
        - .gitlab-ci.yml
        - .ci/**/*
        - dockerfiles/**/*
      variables:
        APP_PUBLIC_PATH: https://tds-preview.xdrnd.cn
        APP_ROUTER_BASE_URL: /tapsdk-doc-intl-$CI_MERGE_REQUEST_ID/
    - if: $CI_COMMIT_BRANCH == "master"
      changes:
        - hk/**/*
        - package.json
        - .gitlab-ci.yml
        - .ci/**/*
        - dockerfiles/**/*
      variables:
        APP_PUBLIC_PATH: https://developer.taptap.cn
        APP_ROUTER_BASE_URL: /docs/
  script:
    - yarn run build-hk:preview
  artifacts:
    paths:
      - hk/build
upload_mr_assets_hk:
  stage: upload
  extends:
    - .mixin_upload
    - .hk_mr_rules
  variables:
    GIT_STRATEGY: none
    ALIYUN_OSS_BUCKET: tds-abd-sh
    ALIYUN_OSS_ENDPOINT: oss-cn-shanghai-internal.aliyuncs.com
    SRC_PATH: hk/build
    DEST_PATH: preview/tapsdk-doc-intl-$CI_MERGE_REQUEST_ID
  needs:
    - build_hk
mr_slack_hk:
  stage: notification
  extends:
    - .mixin_slack
    - .hk_mr_rules
  variables:
    BUILD_LOCATION: hk
    APP_PUBLIC_PATH: https://tds-preview.xdrnd.cn
    APP_ROUTER_BASE_URL: /tapsdk-doc-intl-$CI_MERGE_REQUEST_ID/
  needs:
    - upload_mr_assets_hk
  allow_failure: true
# docker build cn
docker_upload_cn:
  stage: upload
  extends:
    - .build-and-push-image
    - .cn_master_rules
  variables:
    DOCKER_REGISTRY_NAMESPACE: web-frontend
    DOCKER_REGISTRY_REPO: tapsdk-doc-cn
    DOCKERFILE: dockerfiles/cn.Dockerfile
    DOCKER_BUILD_PATH: .
  needs:
    - build_cn
  dependencies:
    - build_cn
deploy_cn:
  stage: deploy
  extends:
    - .deploy-kubefiles-production
    - .cn_master_rules
  environment:
    name: cn/production
  variables:
    PROJECT_PATH: tds/tapsdkdoc
    VALUES_FILENAME: bj_values.yaml
  needs:
    - docker_upload_cn
# docker build hk
docker_upload_hk:
  stage: upload
  extends:
    - .hk_master_rules
    - .build-and-push-image
  variables:
    DOCKER_REGISTRY_NAMESPACE: web-frontend
    DOCKER_REGISTRY_REPO: tapsdk-doc-intl
    DOCKERFILE: dockerfiles/hk.Dockerfile
    DOCKER_BUILD_PATH: .
  needs:
    - build_hk
  dependencies:
    - build_hk
deploy_hk:
  stage: deploy
  extends:
    - .deploy-kubefiles-production
    - .hk_master_rules
  environment:
    name: hk/production
  variables:
    PROJECT_PATH: tds/tapsdkdoc
    VALUES_FILENAME: hk_values.yaml
  needs:
    - docker_upload_hk
# docker build cn rnd
build_rnd_cn:
  stage: build
  extends:
    - .mixin_build
    - .cn_master_rules
  variables:
    APP_PUBLIC_PATH: https://developer.xdrnd.cn
    APP_ROUTER_BASE_URL: /docs/
  script:
    - yarn run build-cn:preview
  artifacts:
    paths:
      - cn/build
docker_upload_rnd_cn:
  stage: upload
  extends:
    - .build-and-push-image
    - .cn_master_rules
  variables:
    DOCKER_REGISTRY_NAMESPACE: web-frontend
    DOCKER_REGISTRY_REPO: tapsdk-doc-cn-rnd
    DOCKERFILE: dockerfiles/cn.Dockerfile
    DOCKER_BUILD_PATH: .
  needs:
    - build_rnd_cn
  dependencies:
    - build_rnd_cn
deploy_rnd_cn:
  stage: deploy
  extends:
    - .deploy-kubefiles-staging
    - .cn_master_rules
  environment:
    name: cn/staging
  variables:
    PROJECT_PATH: tds/tapsdkdoc
    VALUES_FILENAME: rnd_values.yaml
  needs:
    - docker_upload_rnd_cn
# docker build hk rnd
build_rnd_hk:
  stage: build
  extends:
    - .mixin_build
    - .hk_master_rules
  variables:
    APP_PUBLIC_PATH: https://developer-intl.xdrnd.com
    APP_ROUTER_BASE_URL: /docs/
  script:
    - yarn run build-hk:preview
  artifacts:
    paths:
      - hk/build
docker_upload_rnd_hk:
  stage: upload
  extends:
    - .hk_master_rules
    - .build-and-push-image
  variables:
    DOCKER_REGISTRY_NAMESPACE: web-frontend
    DOCKER_REGISTRY_REPO: tapsdk-doc-intl-rnd
    DOCKERFILE: dockerfiles/hk.Dockerfile
    DOCKER_BUILD_PATH: .
  needs:
    - build_rnd_hk
  dependencies:
    - build_rnd_hk
deploy_rnd_hk:
  stage: deploy
  extends:
    - .deploy-kubefiles-staging
    - .hk_master_rules
  environment:
    name: hk/staging
  variables:
    PROJECT_PATH: tds/tapsdkdoc
    VALUES_FILENAME: rnd_intl_values.yaml
  needs:
    - docker_upload_rnd_hk
