include:
  - project: sre/gitlab-ci-templates
    ref: v1
    file:
      - /shared/build-and-push-image.yml
      - /shared/deploy-kubefiles.yml
      - /shared/upload-to-aliyun-oss.yml
stages:
  - build
  - upload
  - deploy
  - notification

# 准备 node 环境，build 和 notification 阶段会用到
.setup_node_env:
  interruptible: true
  image: registry.tapsvc.com/public/node24-bookworm:pnpm10.25.0-1.0.0
  tags:
    - node
  before_script:
    - npm config set registry https://nexus.tapsvc.com/repository/npm-taptap
    - export NODE_OPTIONS=--max_old_space_size=4096
    - yarn install --cache-folder .yarn-cache
  cache:
    - key:
        files:
          - yarn.lock
          - .npmrc
      paths:
        - .yarn-cache

# 公共变量
.changes:
  cn:
    - cn/**/*
    - package.json
    - .gitlab-ci.yml
    - .ci/**/*
    - dockerfiles/**/*
  hk:
    - hk/**/*
    - package.json
    - .gitlab-ci.yml
    - .ci/**/*
    - dockerfiles/**/*

# 基础构建
.default_build:
  stage: build
  interruptible: true
  environment:
    name: independent
  extends:
    - .setup_node_env
  script:
    - yarn run build-$PROJECT:preview
  artifacts:
    expire_in: 1 week
    paths:
      - $PROJECT/build

# 发送 MR & slack 通知
.default_notification:
  stage: notification
  extends:
    - .setup_node_env
  allow_failure: true
  script:
    - git --version
    - npm i -g zx
    - chmod -R 777 ./scripts
    - ./scripts/mr-notification &
    - ./scripts/slack-notification &
    - wait

#  ==== 国内 ====
# mr 
build_cn_mr:
  extends: .default_build
  variables:
    PROJECT: 'cn'
    APP_PUBLIC_PATH: 'https://tds-preview.xdrnd.cn'
    APP_ROUTER_BASE_URL: '/tapsdk-doc-cn-$CI_MERGE_REQUEST_ID/'
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes: !reference [.changes, cn]

upload_cn_mr:
  stage: upload
  environment:
    name: independent
  extends:
    - .upload-to-aliyun-oss
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes: !reference [.changes, cn]
  variables:
    ALIYUN_OSS_BUCKET: tds-abd-sh
    ALIYUN_OSS_ENDPOINT: oss-cn-shanghai-internal.aliyuncs.com
    SRC_PATH: cn/build
    DEST_PATH: preview/tapsdk-doc-cn-$CI_MERGE_REQUEST_ID
    GIT_STRATEGY: none
  needs:
    - build_cn_mr

notification_cn_mr:
  extends:
    - .default_notification
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes: !reference [.changes, cn]
  variables:
    BUILD_LOCATION: cn
    APP_PUBLIC_PATH: https://tds-preview.xdrnd.cn
    APP_ROUTER_BASE_URL: /tapsdk-doc-cn-$CI_MERGE_REQUEST_ID/
  needs:
    - upload_cn_mr

# 线上
build_cn:
  extends: .default_build
  variables:
    PROJECT: 'cn'
    APP_PUBLIC_PATH: 'https://developer.taptap.cn'
    APP_ROUTER_BASE_URL: '/docs/'
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      changes: !reference [.changes, cn]

upload_cn:
  stage: upload
  extends:
    - .build-and-push-image
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      changes: !reference [.changes, cn]
  variables:
    DOCKER_REGISTRY_NAMESPACE: web-frontend
    DOCKER_REGISTRY_REPO: tapsdk-doc-cn
    DOCKERFILE: dockerfiles/cn.Dockerfile
    DOCKER_BUILD_PATH: .
  needs:
    - build_cn

deploy_cn:
  stage: deploy
  extends:
    - .deploy-kubefiles-production
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      changes: !reference [.changes, cn]
  environment:
    name: cn/production
  variables:
    PROJECT_PATH: tds/tapsdkdoc
    VALUES_FILENAME: bj_values.yaml
  needs:
    - upload_cn

# rnd
build_rnd_cn:
  extends: .default_build
  variables:
    PROJECT: 'cn'
    APP_PUBLIC_PATH: 'https://developer.xdrnd.cn'
    APP_ROUTER_BASE_URL: '/docs/'
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      changes: !reference [.changes, cn]
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes: !reference [.changes, cn]
      when: manual

upload_rnd_cn:
  stage: upload
  extends:
    - .build-and-push-image
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      changes: !reference [.changes, cn]
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes: !reference [.changes, cn]
  variables:
    DOCKER_REGISTRY_NAMESPACE: web-frontend
    DOCKER_REGISTRY_REPO: tapsdk-doc-cn-rnd
    DOCKERFILE: dockerfiles/cn.Dockerfile
    DOCKER_BUILD_PATH: .
  needs:
    - build_rnd_cn

deploy_rnd_cn:
  stage: deploy
  extends:
    - .deploy-kubefiles-staging
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      changes: !reference [.changes, cn]
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes: !reference [.changes, cn]
  environment:
    name: cn/staging
  variables:
    PROJECT_PATH: tds/tapsdkdoc
    VALUES_FILENAME: rnd_values.yaml
  needs:
    - upload_rnd_cn

# ==== 海外 ====
# mr
build_hk_mr:
  extends: .default_build
  variables:
    PROJECT: 'hk'
    APP_PUBLIC_PATH: 'https://tds-preview.xdrnd.cn'
    APP_ROUTER_BASE_URL: '/tapsdk-doc-intl-$CI_MERGE_REQUEST_ID/'
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes: !reference [.changes, hk]

upload_hk_mr:
  stage: upload
  environment:
    name: independent
  extends:
    - .upload-to-aliyun-oss
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes: !reference [.changes, hk]
  variables:
    GIT_STRATEGY: none
    ALIYUN_OSS_BUCKET: tds-abd-sh
    ALIYUN_OSS_ENDPOINT: oss-cn-shanghai-internal.aliyuncs.com
    SRC_PATH: hk/build
    DEST_PATH: preview/tapsdk-doc-intl-$CI_MERGE_REQUEST_ID
  needs:
    - build_hk_mr

notification_hk_mr:
  extends:
    - .default_notification
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes: !reference [.changes, hk]
  variables:
    BUILD_LOCATION: hk
    APP_PUBLIC_PATH: https://tds-preview.xdrnd.cn
    APP_ROUTER_BASE_URL: /tapsdk-doc-intl-$CI_MERGE_REQUEST_ID/
  needs:
    - upload_hk_mr

# 线上
build_hk:
  extends: .default_build
  variables:
    PROJECT: 'hk'
    APP_PUBLIC_PATH: 'https://developer.taptap.io'
    APP_ROUTER_BASE_URL: '/docs/'
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      changes: !reference [.changes, hk]

upload_hk:
  stage: upload
  extends:
    - .build-and-push-image
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      changes: !reference [.changes, hk]
  variables:
    DOCKER_REGISTRY_NAMESPACE: web-frontend
    DOCKER_REGISTRY_REPO: tapsdk-doc-intl
    DOCKERFILE: dockerfiles/hk.Dockerfile
    DOCKER_BUILD_PATH: .
  needs:
    - build_hk

deploy_hk:
  stage: deploy
  extends:
    - .deploy-kubefiles-production
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      changes: !reference [.changes, hk]
  environment:
    name: hk/production
  variables:
    PROJECT_PATH: tds/tapsdkdoc
    VALUES_FILENAME: hk_values.yaml
  needs:
    - upload_hk

# rnd
build_hk_rnd:
  extends: .default_build
  variables:
    PROJECT: 'hk'
    APP_PUBLIC_PATH: 'https://developer-intl.xdrnd.com'
    APP_ROUTER_BASE_URL: '/docs/'
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      changes: !reference [.changes, hk]

upload_hk_rnd:
  stage: upload
  extends:
    - .build-and-push-image
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      changes: !reference [.changes, hk]
  variables:
    DOCKER_REGISTRY_NAMESPACE: web-frontend
    DOCKER_REGISTRY_REPO: tapsdk-doc-intl-rnd
    DOCKERFILE: dockerfiles/hk.Dockerfile
    DOCKER_BUILD_PATH: .
  needs:
    - build_hk_rnd

deploy_hk_rnd:
  stage: deploy
  extends:
    - .deploy-kubefiles-staging
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      changes: !reference [.changes, hk]
  environment:
    name: hk/staging
  variables:
    PROJECT_PATH: tds/tapsdkdoc
    VALUES_FILENAME: rnd_intl_values.yaml
  needs:
    - upload_hk_rnd

