// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  store: [
    {
      type: "autogenerated",
      dirName: "store",
    }
  ],
  sdk: [
    {
      type: "autogenerated",
      dirName: "sdk",
    },
    {
      type: "link",
      label: "TapADN",
      href: "https://ssp.dirichlet.cn/docs/",
    },
  ],
  pcstore: [
    {
      type: "autogenerated",
      dirName: "pc-store",
    }
  ],
  design: [
    {
      type: "autogenerated",
      dirName: "design",
    },
    {
      type: "link",
      label: "品牌素材",
      href: "https://www.taptap.cn/about-us/brand-resources",
    },
  ],
  agreement: [
    {
      type: "autogenerated",
      dirName: "agreement",
    },
  ],
  community: [
    {
      type: "autogenerated",
      dirName: "community",
    },
  ],
  shadow: [
    {
      type: "autogenerated",
      dirName: "shadow/tap-online-battle",
    },
  ]
};

module.exports = sidebars;
