server {
    listen       80;
    server_name  developer.xdrnd.cn developer.taptap.cn;

    root   /usr/share/nginx/html/build-cn;
    charset utf-8;

    location / {
        index  index.html index.htm;
    }

    error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    error_page   500 502 503 504  /50x.html;
}

server {
    listen       80;
    server_name  developer-intl.xdrnd.com developer.taptap.io;

    root   /usr/share/nginx/html/build-hk;
    charset utf-8;

    location / {
        index  index.html index.htm;
    }

    error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    error_page   500 502 503 504  /50x.html;
}
